#+BEGIN_COMMENT
.. title: No reply
.. slug: noreply
.. date: 2021-03-11 06:45:38 UTC+05:30
.. tags: text, messages, communication
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT
* Story
Day 1 : No reply.

Day 2 : No reply.

Well, what's the point of being in a messaging ecosystem if we don't yield to
its temptations? To keep the civilization going, one must engage in learned
discourse, vociferous debates and rude emoticon exchanges. Simply put, one must
reply to a friend's message.

Think about it this way:

Millenial Ramayanam. [[https://en.wikipedia.org/wiki/Lakshmana][Lakshmanan]] on his death bed. [[https://en.wikipedia.org/wiki/Rama][Raman]] pings [[https://en.wikipedia.org/wiki/Hanuman][Hanuman]], "/Bro,
ngl, Lak is fried... bad scene... URGENT!... need Sanjeevani ASAP!!!/" Assume a
scenario where Hanuman ignored that text. Now, Gen-Y Raman will not make a call
to Hanuman to assert the gravity of the situation because it simply ain't cool
to call. Couple of days later Hanuman reaches the base camp, smoking chillum,
lit af, and through the chillum smoke he sees another huge smoke screen in front
of him; realises it is coming from Lakshmanan's funeral pyre, and cries WTAF !!!
Now, Raman has one less thing to worry about and [[https://en.wikipedia.org/wiki/Sugriva][Sugreevan]] is still plucking
tulsi leaves one at a time in a Himalayan valley thinking it must be [[https://en.wikipedia.org/wiki/Sanjeevani_(plant)][Sanjeevani]],
going by its smell. What a fate!

Well, luckily, Hanuman, my hero, your hero, our hero, every man's hero, didn't
do that. He replied immediately to Raman: "BRB", took the next flight and
brought the entire freaking mountain. The episode ended with a close-up shot of
Lakshmanan eating protein bars and Greek salad on his path to full fitness and
Sugreevan is smoking chillum in the background. Shubham!

My dear friends, moral of the story is that one must reply to their friend's
messages at the earliest.

Jai Hanuman. Many peace.

--------------------------------------------------

* Terminology

|-------+-----------------------------------------------------------------------------------------|
| Usage | Closest meaning                                                                         |
|-------+-----------------------------------------------------------------------------------------|
| Bro   | Short for brother also known as Bruh a.k.a Bruv.                                        |
| ngl   | not gonna lie                                                                           |
| gonna | going to                                                                                |
| Lak   | short for Lakshmanan                                                                    |
| scene | plight                                                                                  |
| fried | in trouble                                                                              |
| ASAP  | as soon as possible                                                                     |
| lit   | intoxicated or under the influence of some substance; exciting, outstanding, or amazing |
| af    | as f word                                                                               |
| f     | another usage of fornication commonly spelled a f@*k                                    |
| ain't | no f-ing idea what that means                                                           |
| WTAF  | what the actual F word                                                                  |
| BRB   | be right back                                                                           |
|-------+-----------------------------------------------------------------------------------------|









