#+BEGIN_COMMENT
.. title: A story unsaid
.. slug: a-story-unsaid
.. date: 2021-08-19 11:30:15 UTC+05:30
.. tags: poem
.. category: English
.. link: 
.. description: 
.. type: text
#+END_COMMENT

#+OPTIONS: \n:t

The night, soothingly quiet, our poet awoke in her bed.
Eyes wide, a story unsaid, raging in her head.
She opened her book and started scribbling away,
Hoping that the memory of her dream would stay.

Lying on a hammock she thought,
About a piquant dream she caught. 
A story unsaid that she must tell,
Out of her mind, before it fell.

There was the familiar little girl,
Who wore a necklace made of pearl.
Ah..! that curious world inside a crystal bowl,
And indeed the villain who resembled her brother Paul.

Enter villain with an orange balloon in his hand,
Three feet tall, skinny lad was all tanned.
With him he always brought his own music band,
Popular songs they played were all banned.

The orange balloon hovered over his head like a halo,
Her eyes twinkled as she went to say hello.
Will you give me that orange balloon I crave?
Quid pro quo, young lady, he said with a smile, suave.

Shake hands with me for it, little doll?
No, you'll squeeze my fingers like a troll.
Sing a song about Tweedledum but not Tweedledee?
Its impossible! How dare you demand such a deed?
The pearl necklace then, yes?
Oh, no, villains can't have necklaces.

How right you are, here, take it my friend.
Ha-ha, I know, villains always lose in the end.
As she reached out for the balloon, he let it fly,
Ha-ha, where's the fun in not letting it touch the sky?

She woke up with a start, still lying on the hammock,
The pearl necklace was planted safely on her neck.
She opened her book and started scribbling away,
Hoping that the memory of her dream would stay.

The night, soothingly quiet, is coming to its end,
The poet stood in the balcony facing a sea and beyond.
Words on her book rhymed, pearls on her neck shined,
An orange balloon dawned up in the sky and she smiled.

--------------------------------------------------
