#+BEGIN_COMMENT
.. title: Political Ideologies - The beginning
.. slug: pi_one
.. date: 2024-02-07 11:30:15 UTC+05:30
.. tags: politics, podcast
.. category: English
.. link: 
.. description: 
.. type: text
#+END_COMMENT

"Listen -- strange women lying in ponds distributing swords is no basis for a
system of government. Supreme executive power derives from a mandate from the
masses, not from some farcical aquatic ceremony."
says Michael Palin's character in the film Monty Python and the Holy Grail.

Well, in today's episode we begin the series of discourse about supreme power
and masses and governments.

Political ideologies.

It's rather a difficult topic to discuss, isn't it? Where to begin, what to say,
what not to utter, all those epoch defining events, everlasting personalities,
textbook terminologies, its immortal influence in the past, present, and dare I
say, the future! And such is the fatality of this topic that our original plan
to discuss it under "Dumb it down to me" series, was deemed dumb
unanimously. Like a live fish, the harder you try to grasp it, the farther it
escapes. At any rate, an optimistic attempt is vital, so, Welcome, to Hitchens'
Razor!

Liberalism, Conservatism, Left, Right, Fascism, Socialism, Communism,
Libertarianism, Nationalism, Left of centre, Right of centre, uff, and yet, here
we are; One has to wonder, how has these managed to remain relevant to the
modern world?

Now, our attempt to be pragmatic in this episode, say, to rather talk about the
juicy events of the past, than to be tediously academic, wouldn't mean that this
episode would be any less boring than your current imagination. In fact, such a
statement would be euphemistic to a fool's errand around a Mobius band. Such is
the fatality of this topic. If you are not bored already,

Let's begin, by travelling back to a time when the word Ideology did not exist.
* Recap of history
If we are to believe in contemporary consensus, then "Life began in the
ocean". Some creatures subsequently crawled up to the landmass; the
reptiles. They had sex, laid eggs, and abandoned them, moved on to next honey
moon. Reptile nonchalance is criminally underrated.

Then came the birds. They developed wings and feathers to counter the cold. They
had intercourse and more eggs were delivered. But unlike the reptiles, they
started caring about their eggs; by keeping them warm under their wings and
fuselage. The first act of true selfishness.

Enter mammals, with the hitherto unknown notion of storing eggs inside its own
body, inside its own body!. Such was the shock, bird brains accomplished maximum
cognisance, and reptiles simply looked up. Mammals also acquired the habit of
providing protection and nutrition to the offspring. This created attachment
between the youngling and the parent, and it kindled the possibility of learning
by imitation. The beginnings of a true social life. As H.G.Wells put it, "A
teachable type of life had come into the world". And thus we evolved!

Well, the point is, we evolved as a species from Reptiles and Birds to Mammals,
to Hunter Gatherers; we had the early civilizations in Egypt, India, Mesopotamia
and China. We had Aryans and Dravidians, the panchayat or the village system,
the great thinkers Kong Fu-Tse(Confucious), Lao-Tse and Buddha. We had the
kingdom of Persia, the great Greek period, conquests of Alexander, the Mauryan
dynasty, Kautilya and Arthashastra, Hellenistic Greece, Ashoka, Rome, Carthage,
Caesar, Pompey, Augustus, Cleopatra, Jesus of Nazareth, Constantinople, Holy
Roman Church, the Orthodox church, Goths, Huns, Vandals, Islam, Xuanzang(Hsuen
Tsang), Charlesmagne, The fall of Rome, Chalukyas, Pallavas, Rashtrakutas,
Pandyas, Cholas, Ghazni, Genghis Khan, Marco Polo, Timur, Dark Ages, Crusades,
the Renaissance, Age of Science, Age of Enlightenment, Age of Revolution,
and then the FRENCH REVOLUTION happened.

1789

The word ideology was coined, literally a new ‘science of ideas’.

Thence we had Marx, Nietzsche, Electricity, Russian Revolution- part 1, WW- part
1, Russian Revolution - part 2, the Great Depression, WW-part 2, Electronics,
Computers, Cold War, Globalization, Internet, Climate change, Covid and now,
now, as in, the now, now-now, at the moment now.

Now, hopefully that painted a vague timeline of our history. Now, we slip on a
banana peel and fall into the coming of ideologies.
* The coming of Ideologies
It is in Europe where the seeds of modern political ideologies germinated at a
time when politics revolved around religion and religion only. The idea of
nationality which is obvious these days was rather a niche topic then. War was
the most dangerous pandemic in the continent, and religion was the most
important cog in the war machine. Christians, other Christians, Muslims, other
Muslims endlessly fought and killed to protect their version of the
supernatural.
** Feudal System and the Middle class
Violence and disorder prevailed both internally and externally. Strong people
seized land and power, and they built strong castles for own protection, as they
were always under threat from people like themselves. The peasants were not
organized and couldn't defend themselves, so they sold their allegiance to these
lords in castles. The small lords served the bigger lords, and the big lords
bowed to the monarch. The Feudal System!. The Church, and its officials were
also part of this. The idea of equality or of freedom was exempted in this
system.  Thus the middle ages passed under feudal system where peasants lived
miserably. There were occasional revolts from the peasants, but they were
cruelly put down by the upper classes.
*** The bourgeoisie 
There was also another type of people, a floating class including the traders
and merchants. They were not part of the feudal system per se, but they had no
wealth or influence in that society. But the discovery of sea routes radically
changed the fortunes of these daring people. Sea routes opened markets far east
and west of Europe. Asia, America and other parts of the world became accessible
to them.  The middle-class, aka the bourgeoisie thus gathered wealth from global
trade, and the new money fetched them privileges, and eventually power. They
still had two classes above them, the nobles and the clergy, and of course the
king at the top. This segregation based on class is officially called the
/Ancien Regime/, which had policies and taxation controlling the freedom of the
tradesmen. Naturally this was increasingly becoming a hindrance to the
bourgeoisie, as they disliked the fact that the classes above them got money
without work, and representation without taxation.
*** Three 'R's
And then there were the three great movements of the era: Renaissance,
Reformation, and Revolution. The renaissance was about learning, science,
experimental rationalism and asking questions about the universe. Hopefully,
more of Renaissance in another series. Now, Reformation was about religion,
specifically Christianity, and of Revolutions, there were three.
** Reformation
We shall start with the Reformation.

Printing! The Arabs learned paper-making form the Chinese, and Europe learnt it
from the Arabs. Towards the end of 15th century, paper and printing became
common. This meant common people could read books themselves, didn't need a
priest to tell them the content of the Bible.

Rome was the epicentre of European Christianity in this era. At some point the
Roman Church thought heresy hunting would be a fabulous idea. Apparently, there
was fun to be derived and lessons to be taught by burning people alive at stakes
if they questioned the ways of the church. Women were branded as witches and
burnt alive publicly. The infamous Spanish Inquisition formed during this time,
epitomised this sport by underlining the word hunting in heresy hunting. Many
more heinous crimes of unspeakable nature were committed in this time by the
self appointed guardians of god and faith. Early in the 16th century, Martin
Luther, a Christian priest visited Rome, and he was disgusted by its corruption
and luxury. He was a leader who protested against the Holy Roman Church, and
thus formed the christian faction Protestants, against the Roman Catholic,
RC. This Protestant movement gathered pace when young princes and nobles sided
with the protestants to put an end to all attempts made by the Pope to dominate
over them.

In England, Henry VIII, favoured the protestants because he wanted to divorce
his wife and marry another woman, which the Roman Catholic Church, naturally,
was against. So he formed another church called the Church of England, and
established himself as the Head of the Church, and married the woman. He was
then the head of the state and head of the church. Well, why not? god is
omnipresent isn't it?

Italy, France, Austria, and Spain were Catholic at the time. Germany was half
protestant.  The middle class carried the Protestantism with them; wherever they
were strong, protestants thrived. But reformation was not enough to bring down
the kings, they were still powerful and autocratic as ever. The monarch
remained, and waited for the revolutions.
** Netherlands, Switzerland and England
Before we get to the three big revolutions it is worth mentioning Netherlands,
Switzerland and England. Netherlands became republic even before the French
Revolution. There was a heroic but bloody battle that happened between the
merchant classes bourgeoisie of Holland and King Philip II of Spain, who at that
time ruled the region. Switzerland also gained independence around this time
from the Holy Roman Empire after the Thirty Years war.

England, had the parliament in place with two houses, mostly represented by the
lords and nobles at the upper house, and the merchants and wealthy middle class
in the lower house. The parliament eventually became stronger than the monarch,
at a point where its King was beheaded at the orders of the parliament, only to
be later replaced with a puppet from elsewhere in Europe, Germany I
think. England is a curious case, where the Gentlemen and the Bourgeoisie joined
to share power with the king.
** The Three Revolutions
It is interesting that three revolutions happened broadly around the same time
in history. The political revolution in North America, the industrial revolution
in England, and the social revolution in France.
*** American Revolution
War is so demanding, it exhausts the resources of a kingdom, which in turn
demands from its masses, more suffering that is.

For the British Government, the umpteenth war with France meant need for more
money, and they decide to squeeze the colonies to breakeven. The American
colonies resisted, and when the British East India Company tried to force the
colony to buy their tea, the colonists boycotted the act, and some colonists
threw the tea overboard from the ships. Cut to war scenes where France helped
the American Colonists. Cut to British accepting defeat. Cut to the signing of
the Declaration of Independence, with the famous cry, No taxation without
representation. The declaration also said, "All men are born equal" <beat/pause>
except the negroes.

and, in the next episode, The French Revolution.
