#+BEGIN_COMMENT
.. title: Curses and Chances
.. slug: cursesandchances
.. date: 2023-01-25 21:29:20 UTC+05:30
.. tags: poem
.. category: English
.. link: 
.. description: 
.. type: text
.. status: 
#+END_COMMENT

#+OPTIONS: \n:t

The curse is upon all of us.
But we are not at faults!
To collect thoughts and connect dots.

Curse of love, my love,
Curse of care, brother,
Curse of bond, my friend,
Blood, kin, and beyond.

But, for every curse, there is a chance,
That might seem second at first,
but for a lifetime it will stick with us,
Only if we embrace it at self behest,
Alike the tale of hare and tortoise.

Hitherto, we lived in parallel lines,
Belated, your smile crossed mine.
Then we spoke, and we laughed,
And then we sang, and we danced. 
We are thus aware that we were,
For our purpose, joie de vivre!

There are only poems, no poets,
Art owns its own artist.
A deaf maestro's lullaby,
That we could finally,
Feel the friend in you and me,
Where serendipity serenades to our vivacious youth,
And the greatest relief lies in telling the truth.
