#+BEGIN_COMMENT
.. title: Blogging using nikola-github-emacs-orgmode
.. slug: how-to-write-a-blog-using-nikola
.. date: 2018-02-09 01:38:14 UTC+05:30
.. tags: nikola, emacs, github, orgmode, linux, python
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT
* Blog about writing blogs
This blog about writing blogs is written upon request by pestering
friends. Special thanks to all other blogs about writing blogs which
helped me write this blog about writing blogs.
* To know these exist...
| /                          | <                                                         |
|----------------------------+-----------------------------------------------------------|
| [[https://getnikola.com/][Nikola]]                     | Static website generator                                  |
|----------------------------+-----------------------------------------------------------|
| [[https://guides.github.com/activities/hello-world/][Github]]                     | Free website hosting                                      |
|----------------------------+-----------------------------------------------------------|
| [[https://www.gnu.org/software/emacs/tour/][emacs]]                      | Emacs : A wonderful text editor                           |
|----------------------------+-----------------------------------------------------------|
| [[https://en.wikipedia.org/wiki/Org-mode][orgmode]]                    | Headings, Tables, Text formatting, Genetically Awesome!!! |
|----------------------------+-----------------------------------------------------------|
| [[http://docs.python-guide.org/en/latest/dev/virtualenvs/][Python virtual environment]] | A special work place without pollution                    |
|----------------------------+-----------------------------------------------------------|


Curious Columbus-es should then follow the links.
(or) If you just want to get your blog up and running then,
bother not, you shall.
* Well...
The idea is to create a blogging website hosted in /Github/, using a
static site generator software /Nikola/, with the help of /Python
virtual environment/ and then write blog posts using /emacs org mode/.
*** Also
1. I'm using Linux.
2. I will be assuming the name of your blog as 'bottle'
* GitHub 
1. Create a GitHub account.
2. Create a repository with the following name:'bottle.github.io'
3. [[https://guides.github.com/activities/hello-world/][Instructions]].

Once done this, GitHub will host your website in the following
address(URL) : https://bottle.github.io/

Clone(copy) this newborn repository into your local machine a.k.a
personal computer by using the following command:
#+BEGIN_SRC sh
git clone https://bottle.github.io/ $HOME/projects/bottle
#+END_SRC

You will be adding blog posts in ~/projects/bottle directory and will
push them back to GitHub later.
* Python Virtual Environment
If you haven't heard the news yet, Python is a programming
language and Python 3 is here to stay.

Python Virtual environment basically copies python scripts to create a
new workplace. You could install custom packages specific to your
project. 

For e.g. if you wish to have a separate working environment for
cooking vegetables, where you don't want nikola to be installed, 
create a virtual environment called vegetables. 
** Virtual environment wrapper  
Wrapped virtual environment commands for ease of use.
Let "$HOME/virenvs" be our directory for all environments.
#+BEGIN_QUOTE
~As always, names doesn't matter. It is what you do that defines you - Spiderman's ex-girlfriend~
#+END_QUOTE
** Steps
Make sure you have pip (python package manager) in your machine.
And follow the steps :
#+BEGIN_SRC sh
pip install virtualenv
pip install virtualenvwrapper
export WORKON_HOME=$HOME/virenvs
source /usr/local/bin/virtualenvwrapper.sh
mkvirtualenv bottle
workon bottle
#+END_SRC

Now you should see that you have entered the 'bottle' environment.

* Nikola
If you are inside the bottle, then you are ready to install nikola, the
static site generator.
** Installation
#+BEGIN_SRC sh
pip install --upgrade pip 'Nikola[extras]'
nikola plugin -i orgmode
cd $HOME/projects/bottle
git checkout -b sources
#+END_SRC

add a .git ignore file to $HOME/projects/bottle folder with the
following content in it.

#+BEGIN_SRC sh
*.py[cod]
__pycache__
cache
output
.doit.db
#+END_SRC

commit this to git

#+BEGIN_SRC sh
git add .gitignore
git commit -m "Add .gitignore"
#+END_SRC
** Website
Create a website using nikola
#+BEGIN_SRC sh
nikola init bottle
#+END_SRC
Fill in the form that follows.

It should show a success message after form is filled.
Now, nikola will create a new folder called bottle inside
$HOME/projects/bottle, which is unnecessary. So move its contents to
$HOME/projects/bottle folder and delete the extra bottle.
#+BEGIN_SRC sh
mv my_first_site/* .
rm -r my_first_site
#+END_SRC


Your new site 'bottle' can be viewed either locally or globally(using
a new technology called internet). ~The latter will be done later.~

To view your recently created site locally, 
#+BEGIN_SRC sh
nikola build
nikola serve
#+END_SRC

Open browser and enter /localhost:8000/ in the URL bar.

To stop the localhost web service in the terminal hit Ctrl-c.
** Posts
Now, you would want to eat others head by writing blogs. That can be
easily accomplished.

#+BEGIN_SRC sh
nikola new_post -e
#+END_SRC
The -e option will open the post in your text editor of choice;
**** Emacs Org-mode
I will only write the command to prompt new post with org mode and the
configuration.
#+BEGIN_QUOTE
~The self-inflicted awesomeness of emacs and org-mode can only be experienced!~
#+END_QUOTE

You've already installed org mode plugin for nikola in your
installation process. 

Now, append the following to your conf.py file(available in bottle
folder)

#+BEGIN_SRC python
# Add the orgmode compiler to your COMPILERS dict.
COMPILERS["orgmode"] = ('.org',)

# Add org files to your POSTS, PAGES
POSTS = POSTS + (("posts/*.org", "posts", "post.tmpl"),)
PAGES = PAGES + (("stories/*.org", "stories", "story.tmpl"),)

#+END_SRC

Now, to write a post using org-mode,
#+BEGIN_SRC  sh
nikola new_post -e -f orgmode
#+END_SRC
** Comments
If you are using disqus as the commenting system then create a disqus
account and then in your conf.py file,
#+BEGIN_SRC python
# To use comments, you can choose between different third party comment
# systems.  The following comment systems are supported by Nikola:
#   disqus, facebook, googleplus, intensedebate, isso, livefyre, muut
# You can leave this option blank to disable comments.
COMMENT_SYSTEM = "disqus"
# And you also need to add your COMMENT_SYSTEM_ID which
# depends on what comment system you use. The default is
# "nikolademo" which is a test account for Disqus. More information
# is in the manual.
COMMENT_SYSTEM_ID = "your_disqus_account_id"

#+END_SRC
** Publish
use the following commands to launch the site in local host
#+BEGIN_SRC sh
nikola build
nikola serve
#+END_SRC

The 'nikola auto' command automatically updates the site for the
changes you make in your post
#+BEGIN_SRC sh
nikola auto
#+END_SRC

To publish your blog to the so called internet,
#+BEGIN_SRC sh
nikola github_deploy
#+END_SRC

* Thanks
For detailed information : 

1. [[http://streakycobra.github.io/posts/blogging-in-org-mode-with-nikola/][streakycobra]]
2. [[http://cestlaz.github.io/posts/using-emacs-35-blogging/][C'est la Z]]
3. [[http://docs.python-guide.org/en/latest/dev/virtualenvs/][The Hitchhiker's guide to Python]]
4. [[https://getnikola.com/getting-started.html][nikola]]
5. [[http://cestlaz.github.io/stories/emacs/][using emacs]]
6. [[https://www.youtube.com/watch?v=SzA2YODtgK4][Getting started with org mode]]
7. [[https://www.youtube.com/watch?v=oJTwQvgfgMM][org mode : by its creator]]
