#+BEGIN_COMMENT
.. title: City Rain
.. slug: cityrain
.. date: 2021-04-15 21:29:20 UTC+05:30
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
.. status: 
#+END_COMMENT

#+OPTIONS: \n:t


# Before Rain
Like an ancient civilization, the city slept,
In an endless commute, this way of life wept.
In its mirky buildings and sulky streets,  
Boredom grumbled, and happiness crumbled.
Hither and yon, people ran, to make ends meet,
And that's when, the first drop of rain, came to greet.


# Arrival
His highness's arrival was announced by Dhol drums,
Boisterously, it lifted the city out of its doldrums.
Bewitched the wind, into a wicked poltergeist,
Possesed the trees, like an unseen ghost,
Made them dance with no rhyme, nor reason,
The city was put under its spell, in a dry summer season.
Windows were shattered; Wind owes nothing in the end.
Clothes were brandished; One shall never pretend.


# Bus Journey
At the first drop, across the tar road, he boarded a bus, red,
Sitting by a window, he peered outside - pandemonium appeared.
Citizens with books, and bags, and sarees above their head,
Steam rising, from a packed tea shop in the distance, up ahead,
A woman wrestling with wind, to ignite a cigarrete,
Strolling while nature is mopping; a singular etiquette.
A buoyant umbrella was floating in a whirlwind, 
Nature mocking the anticipation of humankind.
The rain gained momentum as the bus coughed forward,
He looked behind and saw memories travelleing backward.
Closed his eyes, the downpour deluged his face with euphoria,
A song surfaced from his childhood that rhymed with liquid nostalgia.


# reader
At the first drop, she picked up the book, her precious company,
The wooden arm chair, beckoned her from the spacious balcony;
Feet up on the chair, rocking back and forth,
She witnessed the sky coalesce with earth.
Closed her eyes; her breath flooded heart with petrichor,
Opened the book; her brain vessels capsized in bibliochor.
For once, her heart and brain agreed to this moment,
Purpose of life is knowlegde; it makes you content.


# football
At the first drop, they said, let's keep playing,
This can't get any better, keep the ball rolling.
The rain couldn't drench their jerseys wet,
For they were already saturated in sweat.
Raindrops crossing flood lights was quite a sight,
Win this special game, they must, with all their might.
Awaits, a hot water bath, a biryani, and perhaps a drive into the night,
When the city shines bright, the night grows young until the first light.


# Sensual Couple
At the first drop, he sought her presence,
She was not found in their residence.
He looked at the flight of stairs,
Spun on his feet, and went to the terrace.
There she stood staring at the sky,
Palms open, her hands were lifted shoulder high.
Her pink clothes soaked from head-to-toe,
He moved closer and hugged her apropos.
She stepped on his feet; He kissed on top of her head,
Her hands wrapped around his chest, where her face rested.
In that chilling juxtaposition, they stood in silence,
Under the rain, they melded into the timeless ambience.


# poet
At the first drop, Poet moved to the kitchen,
For a cup of tea with a hint of mint and lemon.
The curtains swung over the room irking the shadows,
A venerable fountain pen lay on the table in its repose.
The pen kissed the paper, then and back again,
Until Poet read the words, "City Rain".
