#+BEGIN_COMMENT
.. title: City Rain
.. slug: cityrain
.. date: 2021-04-15 21:29:20 UTC+05:30
.. tags: poem
.. category: English
.. link: 
.. description: 
.. type: text
.. status: 
#+END_COMMENT

#+OPTIONS: \n:t

# Before Rain
Like an ancient civilization, the city slept,
In an endless commute, its way of life wept.
In mirky buildings and sulky streets,  
Boredom grumbled and happiness crumbled.
Hither and yon people ran to make ends meet,
And that's when the first drop of rain came to greet.

--------------------------------------------------

# Arrival
His highness's arrival was announced by Dhol drums,
Boisterous, it lifted the city out of its doldrums.
Bewitched the wind into a wicked poltergeist,
Which possessed the poor trees at first sight.
Made them dance with no rhyme, nor reason,
The city was under its spell in a summer season.

--------------------------------------------------

# Bus Journey
At the first drop, across the tar road, he boarded a bus, red,
Sitting by a window, he peered outside - pandemonium manifested.
Citizens with books, and bags, and sarees over their head,
Steam rising, from a packed tea shop in the distance, ahead,
A woman wrestling with nature to ignite a cigarette,
He shared a laugh with nature at this singular etiquette.
An umbrella afloat, weightless in a whirlwind, 
A fine mocking at humankind failing to take a hint.
The rain gained momentum as the bus coughed forward,
He looked behind and saw memories travelling backwards.
As he closed his eyes, a downpour of nostalgia deluged his face,
A boy buoyant in his village pond, droplets of euphoria in his gaze.

--------------------------------------------------

# reader
At the first drop, she picked up the book, her precious company,
The wooden arm chair beckoned her from the spacious balcony.
Feet up on the chair, rocking back and forth,
She witnessed sky coalesce with the earth.
A deep breath flooded her heart with petrichor,
An open book capsized her brain vessels in bibliochor.
For once, her heart and brain agreed,
Knowledge is the purpose of her life ahead.

--------------------------------------------------

# football
At the first drop, they said, let's keep playing,
This can't get any better, keep the ball rolling.
The rain couldn't drench their jerseys wet,
For they were already saturated in sweat.
Raindrops across flood lights, quite a sight,
A special game, they must win this with all their might.
A hot shower awaits, a Biryani, and perhaps a drive into the night,
When the city shines bright, and it grows young until the first light.

--------------------------------------------------

# Sensual Couple
At the first drop, he sought her presence,
She was not found inside their residence.
He stared at the flight of stairs,
A hop, skip, and a jump to the terrace.
There she stood staring at the sky,
Palms open, her hands lifted shoulder high.
She wore pink clothes soaked from head-to-toe,
He moved closer and hugged her apropos.
She stepped on his feet as he kissed on top of her head,
Shaking hands wrapped around his chest, thus her face rested.
In that chilling juxtaposition they stood in silence,
Under the rain, pure love melded into a timeless ambience.

--------------------------------------------------

# poet
At the first drop, poet slid into the kitchen,
A cup of tea with a hint of mint and lemon.
The curtains swung over the library irking the shadows,
A venerable fountain pen lay on the table in its repose.
The pen kissed the paper, then and back again,
Until poet read the words, "City Rain".

--------------------------------------------------
