#+BEGIN_COMMENT
.. title: Cold blooded comedy blasphemy
.. slug: cold-blooded-comedy-blasphemy
.. date: 2018-03-19 18:35:56 UTC+05:30
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

#+OPTIONS: \n:t


* Cold blooded comedy blasphemy
The Director is waiting in the car. 
Assistant enters. 

A: Stanley, they are not laughing.
S: What do you mean they aren't laughing?
S: Did you hear them not laughing?  It is a comedy movie.
A: I know sir. But there is no laughter. Humour is hiding. 
S: Ridiculous, ridiculous.
S: The script was hilarious. I wrote it.
A: They are just silent sir. There is a powerful sound vacuum.
S: But, I remember it was funny. Didn't it tickle your funny bone?
A: Yes sir, it did tickle me.
S: The actors also were hysteric during the filming.
S: They had time of their life doing what I told them to do.
A: Right Sir. They did laugh their bottoms up.
S: Why are the audience such cretins?
A: I don't know sir. But some of them even left in between the show.
S: That's cold blooded comedy blasphemy! 
A: I couldn't take it as well sir. That's why I came out to tell you.
S: Thanks Amy.
S: Let's get out of here. Where is our driver?
A: I think he inside the hall watching the movie.
S: Thank goodness, at least the boy has some sense of humour.
A: Sir, here he comes. In his face, I see, Sir... Satisfaction!!!
S: Wonderful, Wonderful!

Driver enters...

S: David, Did you enjoy it?
A: Tell us, how was it?
D: It was relaxing. Thanks for asking.
S: Thank God. All that not in vain.
A: Is it over already? I thought it went for another 30 minutes.
D: Sorry what? No, I finished it quickly.
S: Were you not in the theater?
A: Watching the movie?
D: Oh, no.. no.. I was in the toilet.
