#+BEGIN_COMMENT
.. title: Crime scene
.. slug: crime-scene
.. date: 2018-10-22 23:00:56 UTC+05:30
.. tags: crime, cooking, 
.. category: writing
.. link: 
.. description: 
.. type: text
#+END_COMMENT

#+OPTIONS: \n:t

--------------------------------------------------

*/What happened?/*

I was reading a book, and suddenly heard a loud noise from outside.

*/Can you please elaborate?/*

That's what sir BANG!, and seconds later, a second BANG.

*/Can you try to recreate your evening till the incident?/*

Yes sir. 
Yesterday, I came back late from work. I had to attend two more meetings
after that sir. "Mrs. Elusive Luck's birthday, my god", both meetings
got cancelled. I was happy to do my homework from morning's music class. 
I practised music for an hour or, maybe little more sir. It was a good 
workout, and by the end, I was sweating, and trembling from top to bottom. 
I wrapped the scene, and was hungrily wandering inside, and I found a
banana on my study table. Who keeps a banana on study table sir?  
Well, I did, yesterday morning. Sync sir, Unbelievable.

*/Alright, then what?/*

Thought of cooking dinner sir. Dosa in my mind, I found couple of duck eggs in
the fridge. 'Egg Dosa' creeped, sorry crept into my head. I brought Dosa batter,
and eggs outside to warmth. Roasted some curry leaves sir, and ground them with
chillies to a green paste. Fried some Coin Pappads as well.

An eerie silence lurked in the kitchen while I was chopping onions. I added salt,
and a pinch of turmeric to the onions, whereupon I introduced our dear eggs to
Madame la Guillotine, CRACK!, its viscous yellow head slipped in to the bowl.
I stirred a motley mixture after that. When the pan on the stove started
whispering to wind, I threw a water blanket over it, to which, it hissed, 
and shot sodium-in-water kind of tantrums at me. I calmly slid its burning bubbles
to the sink. Then, I painted a solar system on the pan with the batter. The
system needed to be perfect. A subtle press in the center was by followed by 
concentric Sufi whirling. It must spread into a round Gaussian distribution,
and scatter a Brownian motion of batter pores. The pores would channel the steam
upwards, cooking the layers above it, along its itinerary. Then I sprayed oil,
and smeared the roasted curry chilli green paste over the Dosa. Few seconds
later, I massaged the duck egg mash on the green pasture. 
Juxtaposition, hitherto unrealistic, was accomplished.

Sir, then I flipped the Dosa, and waited for some time, for the other side to get
cooked, and kept the Dosa aside. Made one more Dosa like that sir. I ate both
Dosas with Maple syrup, Chammanthi Podi, and Coin pappads sir.
Sync sir, Unbelievable.

*/What is a Chammanthi podi?/*
Sir, this is not the appropriate time sir. Maybe later.

*/Then?/*

I had a Pear, drank 350ml water, brushed my teeth, wrote a blog post, washed
my legs, and went to bed. I continued reading the book "To kill a mockingbird",
when suddenly heard a loud noise from outside sir.

*/Is that it?/*
Yes sir.

/Well, write down your address and phone number. You will have to come to the/
/police station when called upon, to give your statement about yesterday's/
/incident./

Sure sir. Done deal.
