#+BEGIN_COMMENT
.. title: Crime scene
.. slug: crime-scene
.. date: 2018-10-22 23:00:56 UTC+05:30
.. tags: crime, cooking, dosa, food
.. category: writing, serious comedy
.. link: 
.. description: 
.. type: text
#+END_COMMENT

#+OPTIONS: \n:t

--------------------------------------------------

*/What happened?/*

I was reading a book, and suddenly heard a loud noise from outside.

*/Can you please elaborate?/*

That's what sir, BANG!, and seconds later, a second BANG.

*/Will you be able to recreate your evening till the incident?/*

Yes, sir. Yesterday I came back late from work, to attend two more late evening
meetings. Ms. Elusive Luck's birthday, *my god*, both meetings got cancelled 
at my arrival. So, I practised music for what I thought was an hour.
Sir, It was a good workout, and by the end I was sweating and shivering
from forehead to heels. I wrapped the set, and was hungrily wandering indoors.
That's when i saw the most beautiful thing on my study table. A banana!
Who keeps a banana on a study table, sir? Well, I did, yesterday morning. 
Sync sir, Unbelievable.

*/Alright, then what?/*

Sir, i thought of cooking dinner. Dosa in my mind, I found couple of duck eggs
in the fridge. 'Egg Dosa' creeped, sorry, crept into my head. I fetched Dosa
batter and eggs to the warmth outside. Roasted some curry leaves, and ground
them with chillies into a lush green paste. Fried some Coin Pappads as well.

An eerie silence lurked in the kitchen while I was chopping onions. I added
salt, and a pinch of turmeric to the onions. Then I introduced our dear eggs
to Madame la Guillotine, CRACK!, its viscous yellow head crashed into the bowl.
I stirred a motley mixture with all that. When the pan on the stove, started
whispering to the winds, i threw a water blanket over it. The pan hissed, 
and shot sodium-in-water sorta tantrums at me. I calmly slid the hot bubbling
bubbles into the sink. Then, I painted a solar system on the pan with batter.
The system had to be perfect. A subtle press in the center was by followed by
concentric Sufi whirling. It must spread into a round Gaussian distribution,
and scatter a Brownian motion of batter pores. The pores would channel the 
steam upwards, cooking the layers above en route its itinerary. Then, i
sprayed oil, and smeared the lush green paste on top of the maturing Dosa.
Few seconds later, I massaged the duck egg mash on the green pasture.
Juxtaposition, hitherto unrealistic, was accomplished.

Sir, I flipped the Dosa, and waited for the other side to get cooked, flipped it
again and, kept the Dosa aside. Made one more Dosa like that, sir. Later,I ate
both Dosas with Maple syrup, Chammanthi Podi, and Coin pappads sir.  
Sync sir, Unbelievable.

*/What is a Chammanthi podi?/*
Sir, this ain't the appropriate time sir. Maybe later.

*/Then?/*

I had a Pear, drank 350ml of water, brushed my teeth, wrote a blog post, washed
my legs, and went to bed. I continued reading the book "To kill a mockingbird",
when suddenly heard a loud noise from outside sir.

*/Is that it?/*
Yes sir.

/Well, write down your address and phone number. You will have to come to the/
/police station when called upon, to give your statement about yesterday's/
/incident./

Done deal, sir. Many peace.
