#+BEGIN_COMMENT
.. title: പ്രേമോനിഷൻ
.. slug: premonition
.. date: 2026-01-24 09:25:45 UTC+00:00
.. tags: premam, comedy, payyan, പയ്യൻ, പ്രേമം 
.. category: Malayalam
.. link: 
.. description: 
.. type: text
.. status:
#+END_COMMENT

'ഇരിക്കു, ഇരിക്കൂ.'

'എന്താ പേര്?'

/'ഇന്ദുലേഖ'/

'ശ്വാസം ഒന്ന് ഉള്ളിലേക്ക് എടുക്കൂ.'

'വിട്ടോളൂ '

'ഒന്ന് കൂടി, പ്ളീസ്.'

'റിലീസ്.'

'ഒന്ന് തിരിഞ്ഞിരിക്കൂ '

'മുടി മുന്നിലേക്കിട്ടോട്ടെ ?'

'/ഹാ/'

'ശ്വാസം എടുക്കൂ.'

'വിടൂ.'

'എഗൈൻ'

'എഗൈൻ '

'താങ്ക്സ് '

'തിരിഞ്ഞോളൂ '

'കണ്ണ് തുറക്കൂ '

'ഒന്നിടത്തോട്ട് '

'വലത്തോട്ട് '

'നൈസ് '

'രണ്ട് കണ്ണും '

'ഇടത്തോട്ട് '

'വലത്തോട്ട് '

'ഇനി ഒന്ന് നാക്ക് പുറത്തിട്ട് 'സ' എന്ന്  പറയൂ.'

'നാക്ക് ഉള്ളിലിട്ടൊള്ളൂ, എന്നിട്ട് 'സ്' ഒന്ന് സസ്‌റ്റൈൻ ചെയൂ. '

'ശ്രുതിയിലാണല്ലോ.'

'ഇനി  'പ' ഒന്ന് സസ്‌റ്റൈൻ ചെയൂ.'

'കുഴപ്പല്യ.'

'നെറ്റിയിൽ ചെന്നികുത്തോ മറ്റോ?'

'ചെവിടെ പിന്നിൽ വേദന വല്ലതും?'

'ഐ സീ. '

'നൗ, മേ ഐ പ്ളീസ് ടേക്ക് യുർ ഹാൻഡ്?'

(പൾസ് ചെക്ക്)

'കാലിൽ ആൻകിൾ സ്വെല്ലിങ് ?'

'ഒന്നെണിക്കൂ. എന്റെ കയ്യിൽ സപ്പോർട്ട് ചെയ്‌തോളൂ. ഇടത്തേ കാലിൽ ഊന്നി മുതുക് വളയാതെ തിരിയൂ. '

'സ്വിച്ച് ഹാൻഡ്‌സ് പ്ളീസ് '

'തിരിയൂ'

'ഇരുന്നോള്ളൂ, ട്ടോ.'

(അവിടെ മേശയിൽ വച്ചിരുന്ന പുസ്തകവും പേനയും എടുക്കുന്നു)

'ഇനി പറയൂ, എന്താ പ്രശ്നം?'

'ഞാൻ എന്റെ അമ്മയെ പിക്ക് ചെയ്യാൻ വന്നതാണ്. അമ്മ ഇവിടെ ഡോക്ടറാണ്.'

'ഈസ് ഷി നൗ?'

(അമ്മ കയറി വരുന്നു)

'ആരാ ഇന്ദു ഇത് ?'

'അറിയില്ല അമ്മേ'

'അല്ല, താൻ...'

(ഒരു ശരാശരി കുസൃതിച്ചിരി അവന്റെ വദനത്തിലമർന്നു)
 
'ഹലോ മാം, ഞാൻ ആർ. എൽ. ശ്രീവത്സൻ.'

'അതിന്?\\
ഇതെന്റെ കൺസൽട്ടിങ് മുറിയല്ലേ?'

'ഓ, ഈസ് ഇറ്റ്? ഏറ്റവും മികച്ച മുറിയാണ് മാം. കരതലാമലകമാം അഭിരുചി. മാലിയുടെ ചിത്രം മനോഹരം.\\
സോറി, ഇത് വഴി പോയപ്പോൾ, ഞാൻ, \\
സോറി, കുട്ടി അക്ഷമയോടെ കാത്തിരിക്കുന്നത് കണ്ടപ്പോൾ, ഞാൻ,\\
സോറി, പേഷിയന്റ് ആണെന്ന് കരുതി.'

'ടോ, അതിന് താൻ ഡോക്ടറാണാ?'

'ഒരിക്കലുമല്ല മാം, ഭാവി ഒട്ടും കുറയ്‌ക്കേണ്ടതില്ലാത്ത ഒരു ജൂനിയർ ആർട്ടിസ്റ്റ് ആകുന്നു നാം. അടുത്ത ബിൽഡിങ്ങിൽ
ഷൂട്ടിംഗ് നടക്കുന്നത് അറിയാമല്ലോ. അവിടെന്ന് ചാടിപ്പോന്ന ഒരിനം പറവയാകുന്നു. പക്ഷേ
പേടിക്കാനൊന്നുമില്ല, മിസ്സ് ഇന്ദുലേഖയ്ക്ക് ഒരു കുഴപ്പവുമില്ല. \\
ഷീ ഈസ് എ സുന്ദരി.'

'എന്ത്?'
 
'ഞാൻ വരട്ടെ, ദിനത്തിന്റെ മിച്ചം നിങ്ങൾക്ക് മംഗളമായി ഭവിക്കട്ടെ. ബൈ മാം.....; ബൈ മിസ്സ്'.

(അഭി ന ജാഓ എന്ന് മൂളികൊണ്ട് നടന്ന് മറയുന്നു)
* ഇന്ദുലേഖയുടെ മനസ്സിലുണ്ടായ ചിന്തകൾ
/'ങ്ഹേ, ഇതാരാ? തരക്കേടില്ലല്ലോ... പോയോ.'/

(പാട്ട് മൂളുന്നു)\\
'അഭി ന ജാഓ ഛോട് കർ\\
കെ ദിൽ അഭി ഭര നഹി'

(ഫോൺ ശബ്ദം)\\
'ആ, പറയൂ അമ്മേ.'

'ഇന്ദൂ, കുറച്ചു നേരം കൂടി, സോറി, ഒരു 15 മിനിറ്റ്സ്. '

'വേഗം പ്ളീസ്. '

'ഇരുന്ന് ബോറടിച്ചോ?'

'പിന്നല്ലാതെ. മെയ്ക് ഹേയ്സ്റ്റ്.'
 
(ഫോൺ ബന്ധം മുറിക്കുന്നു. കണ്ണുകൾ ജനാലയിലേക്ക് പായുന്നു. \\
വീണ്ടും ഇയാളോ. ഈ വെള്ള കോട്ട് ഉണ്ടായിരുന്നില്ലല്ലോ അങ്ങോട്ട് പോയപ്പോൾ. ഹൈ, ഇങ്ങോട്ടേക്കാണല്ലോ.)

/'അല്ല, ഞാനെന്തിനാ ഇപ്പൊ എണ്റ്റെ?/'

'ഇന്ദുലേഖ'

/'ശ്വാസമല്ലേ, എടുത്തേക്കാം. ബ്രത്ത്-ട്ടേയ്കിംഗ് ആണെന്ന് തോന്നിക്കോട്ടെ. ഹഹഹ./'\\
/'ഛെ, ഒട്ടും നിലവാരമില്ലാത്ത തർജ്ജമ്മ ഹാസ്യം./'

/'അല്ല, ഇതെന്റമ്മടെ സ്തെതസ്കോപ്പല്ലേ? ആരാ ഈ വിദ്വാൻ? എന്നെ എന്തിനാ പരിശോധിക്കുന്നേ? ഓ, ഇടം കൈയനാണല്ലോ, കൊള്ളാം./'

/'വീണ്ടും ശ്വാസം. കൈതണ്ട തരക്കേടില്ല. ചരടൊന്നുംകെട്ടി വൃത്തികേടാക്കിയിട്ടില്ല. ഇനി നാസ്തികനായിരിക്കുമോ ദൈവമേ...?/'

/'തിരിയാനോ? ഓ തിരിയാലോ/'

'ഹാ'

/'അയ്യോ, അത് അഫ്ഫർമേറ്റീവ് ഹാ അല്ല; ഇമ്-പെരെറ്റിവ്  'ഹാ?' ആയിരുന്നു./'\\
/'എന്റെ കേശഭാരം, അത് കയ്യിലെടുക്കുകയോ? കേശവാ നീയിത് കാണുന്നില്ലേ? നീ സമ്മതിച്ചിട്ടല്ലേ? ഞാൻ സമ്മതിച്ചോ?/'
/'ഹാങ്ങ് ഓൺ. കേശവനും കേശത്തിനും ബന്ധമില്ല ലെ...? കേശി എന്ന അവഗുണനെ പൂശിയതിനാണോ? എന്തോ?/'

/'ദേ, വീണ്ടും ശ്വാസം./'

/'ഓ/'

/'ഓ/'

/'വീണ്ടും തിരിയാനോ, ഓ അതിനെന്താ./'

/'കണ്ണ് തുറക്കാനോ. തിരഞ്ഞെടുപ്പ് സമയമായില്ലല്ലോ. ഹഹഹഹ./'

/'എന്റെ കണ്ണ് നോക്കുന്നതിൽ, വിദ്വാന്റെ കണ്ണും മൂക്കും വിടരുന്നുണ്ടല്ലോ. ഡൈലേറ്റഡ് പ്യുപ്പിൾ കൊണ്ട് മുദ്രകൾ./'

/'എന്ത്,  നാക്ക് പുറത്തിട്ട് സ പറയാനോ. അതെങ്ങനെയാ മാഷേ? ശ്രുതി ചേരില്ല./'

/'ഓ, സസ്‌റ്റൈൻ ചെയ്യാം. ശ്രുതിയിൽ തന്നെ ചെയ്യാം./'\\
/'ശ്രുതി മനസ്സിലാക്കിയല്ലോ. നീറ്റ്./'

/'ഇനിയെന്താ? 'പാ'യോ. ഇത്ര പെട്ടെന്ന് പായിലേക്ക് നീങ്ങിയോ കാര്യങ്ങൾ. കേശവാ എന്തായിത്?/'\\
/'ഹഹഹ, എന്നെകൊണ്ടിതൊക്കെ എങ്ങനെ സാധിക്കുന്നു./'

/'ചെന്നികുത്തോ? നെറ്റിയിൽ തൊട്ടു... അമ്പോ!/'

'ഇല്ല'

/'ഡേയ്, ചെവിടെ പിന്നിൽ തൊടരുത്. അത് വീക്ക് പോയിന്റ് ആകുന്നു. ഈശ്വരാ... തൊട്ടു. ഞാൻ കണ്ണടച്ചതും,
നെറ്റി ചുളിച്ചതും, തോൾ വെട്ടിച്ചതും ഈ പയ്യൻ ശ്രദ്ധിച്ചിട്ടുണ്ടാകുമോ?/'

/'ടേക്ക് മൈ ഹാൻഡ്... അതെനോടാണോ, അച്ഛനോടല്ലേ ചോദിക്കേണ്ടത്?/'

/'പൾസ്സ് നോക്കരുത്. നെഞ്ച് പിടയ്ക്കുകയാണ്./'

/'എണീക്കാൻ എന്തിനാ തന്റെ സപ്പോർട്ട്? എനിക്ക് സ്വയം... എന്തായാലും സൂത്രത്തിൽ ഇയാളുടെ പൾസ്സ് ഒന്ന്
നോക്കാം. ബലിഷ്ഠമായ കൈകൾ. ഇയാൾക്ക് ഇരുമ്പ് കമ്പനിയുടെ പരസ്യത്തിൽ അഭിനയിക്കാൻ പൊയ്ക്കൂടേ?/'

/'സ്വിച്ച് ഹാൻഡ്‌സ്? ഇതെന്താ ടാംഗോ ഡാൻസാണോ? ആണോ? ആണോ ഇന്ദു?/'

/'കഴിഞ്ഞോ?/'

/'ഓ, തിരിയാം./'

/'ഓ, ഇരിക്കാം./'

/'പ്രശ്നമോ? ദാ, അമ്മ വരുന്നുണ്ടല്ലോ./'

'ഞാൻ എന്റെ അമ്മയെ പിക്ക് ചെയ്യാൻ വന്നതാണ്. അമ്മ ഇവിടെ ഡോക്ടറാണ്.'

'ഈസ് ഷി നൗ?'

(അമ്മ കയറി വരുന്നു)

'ആരാ ഇന്ദു ഇത്?'

'അറിയില്ല അമ്മേ.'

'അല്ല, താൻ...'

(ഒരു ശരാശരി കുസൃതിച്ചിരി അവന്റെ വദനത്തിലമർന്നു)
 
'ഹലോ മാം, ഞാൻ ആർ. എൽ. ശ്രീവത്സൻ.'

'അതിന്?\\
ഇതെന്റെ കൺസൽട്ടിങ് മുറിയല്ലേ?'

'ഓ, ഈസ് ഇറ്റ്? ഏറ്റവും മികച്ച മുറിയാണ് മാം. കരതലാമലകമാം അഭിരുചി. മാലിയുടെ ചിത്രം മനോഹരം.\\
സോറി, ഇത് വഴി പോയപ്പോൾ, ഞാൻ, \\
സോറി, കുട്ടി അക്ഷമയോടെ കാത്തിരിക്കുന്നത് കണ്ടപ്പോൾ, ഞാൻ,\\
സോറി, പേഷിയന്റ് ആണെന്ന് കരുതി.'

'ടോ, അതിന് താൻ ഡോക്ടറാണാ?'

'ഒരിക്കലുമല്ല മാം, ഭാവി ഒട്ടും കുറയ്‌ക്കേണ്ടതില്ലാത്ത ഒരു ജൂനിയർ ആർട്ടിസ്റ്റ് ആകുന്നു നാം. അടുത്ത ബിൽഡിങ്ങിൽ
ഷൂട്ടിംഗ് നടക്കുന്നത് അറിയാമല്ലോ. അവിടെന്ന് ചാടിപ്പോന്ന ഒരിനം പറവയാകുന്നു. പക്ഷേ
പേടിക്കാനൊന്നുമില്ല, മിസ്സ് ഇന്ദുലേഖയ്ക്ക് ഒരു കുഴപ്പവുമില്ല. \\
ഷീ ഈസ് എ സുന്ദരി.'

'എന്ത്?'
 
'ഞാൻ വരട്ടെ, ദിനത്തിന്റെ മിച്ചം നിങ്ങൾക്ക് മംഗളമായി ഭവിക്കട്ടെ. ബൈ മാം.....; ബൈ മിസ്സ്'.

(അഭി ന ജാഓ എന്ന് മൂളികൊണ്ട് നടന്ന് മറയുന്നു)
* അരം + അരം = ഒരുതരം. രണ്ടും കണക്ക്
(അമ്മ ചിരിക്കുന്നു)\\
'ഹഹഹ, വാട്ട് എ ലാഡ്‌. ഇന്ദൂ, വിദ്വാൻ വേണ്ടില്ല, ലേ?'

ആ  ചോദ്യത്തിന് പക്ഷെ ഇന്ദുലേഖ മനസ്സിൽ പോലും ഉത്തരം പറഞ്ഞില്ല.
അവളുടെ തത്സമയ പെരുമാറ്റം നടന്നകലുന്ന കാൽപെരുമാറ്റങ്ങളിൽ പതുങ്ങി. വിശാലമായ അക്ഷികൾ പോയ
വഴി പിന്തുടർന്നു. ആർദ്രമായ മനസ്സ് കൂട്ടിന് ചെന്നു. ബഹുവിരസം തന്നെയെന്ന് തീർച്ചപ്പെടുത്തിയ നിമിഷങ്ങളിൽ
ദൂരതീരത്തെ നാലിലൊരു സമീരനെപ്പോലെ ഈ മുറിയിൽ നിന്നും ആർ. എൽ. ശ്രീവത്സൻ അവളുടെ സൈക്കിയെ
'കിഡ്നാപ്പ്' ചെയ്തിരിക്കുന്നു. ആ മന്ദമാരുതസ്പർശത്തിൽ അസംശയം സ്വഭാവവിപരീതേന അവളൊന്ന്
കുണുങ്ങിപ്പോയി.

'ഇന്ദൂ.'

'അമ്മേ...' (വ്രീളാവിവശതയിൽ നിന്നും സ്വയം വീണ്ടെടുത്ത് അല്പസ്വല്പം ബാലിശത്തോടെ:) 'കല, എന്റെ പല ദൗർബല്യങ്ങളിൽ എനിക്ക് ഏറ്റവും പ്രിയപെട്ടതാകുന്നു.'

(സ്വതേ നതഭ്രൂവായ അമ്മയുടെ പുരികങ്ങൾ വിശകലനശേഷിയോടെ കൂടുതൽ വളഞ്ഞു)
'അതുകൊണ്ട്?'

'എനിക്കൊരു ബോധോദയമുണ്ടായി.'

'എന്ത്?'

'സോറി, ഗതസംശയം പ്രണയത്തിലലിയാൻ പോകുന്നവളെങ്കിലും, ഞാൻ, \\
സോറി, മാലിയെ തിരിച്ചറിഞ്ഞ അവന്റെ താലി, ഞാൻ, \\
സോറി, പ്രേമോനിഷൻ, അതെ പ്രേമോനിഷൻ, അല്ല, ഞാൻ, \\
സോറി, അതൊരു വാക്കല്ല, അങ്ങനെയൊരു വാക്കില്ല, അത്, ഞാൻ, \\
സോറി, എനിക്ക് മുൻ‌കൂർ വെറുതെ തോന്നിയതാണ്. \\
സോറി, അല്ലെങ്കിലും പ്രേമമില്ലാതെ മനുഷ്യനുണ്ടോ?'

'ഇന്ദുലേഖേ...'\\ 
(ആ വിളി.., അങ്ങനെ വിളിച്ചത് അവളുടെ തായ്ക്കുലമല്ലായിരുന്നു, \\
ആ വിളി.., നിരാലംബയായ പ്രണയരോഗിയെ മുന്നിൽ കണ്ട ഭിഷഗ്വരയുടേതായിരുന്നു.)  
