#+BEGIN_COMMENT
.. title: Yellow Balloon
.. slug: yellow-balloon
.. date: 2021-08-19 11:30:15 UTC+05:30
.. tags: poem
.. category: English
.. link: 
.. description: 
.. type: text
#+END_COMMENT

#+OPTIONS: \n:t

The night, soothingly quiet, Poet awoke in her bed.
Eyes wide, a story unsaid, raging in her head.
She opened her book and started scribbling away,
With hope that the memory of her dream would stay.

Lying on a hammock she thought,
About a piquant dream she caught. 
An unsaid story that she must tell,
But out of her mind it suddenly fell.

It was about a familiar young girl,
Who wore a necklace made of pearl.
Ah..! that curious world inside a crystal bowl,
And indeed the villain who made the story whole!

Enter Villain, with a yellow balloon in his hand,
Seven feet tall, skinny lad was all tanned.
With him he brought his own music band,
Popular songs that it played were all banned.

Yellow balloon hovered above his head like a halo,
Her eyes twinkled as she went to say hello.
Will you give me that yellow balloon I crave?
Quid pro quo, the pearl necklace, that I will take to my grave.

The necklace? no, no!
Oh dear, why is that so?
Because you’re the villain in this story!
Yes, but villains are also part of history.

No, I know, villains always lose in the end.
Right you are! Here, take the balloon my friend.
As she reached out for the balloon, he let it fly,
Ha-ha! where's the fun in not letting it touch the sky.

She woke up with a start, still lying on her hammock,
The pearl necklace was planted safely on her neck.
Opened her book and started scribbling away,
With hope that the memory of her dream would stay.

The night, soothingly quiet, is coming to its end,
The poet now stood in her balcony facing the cold wind.
Words rhyming on her book, Pearls shining on her neck,
As she smiled at an yellow balloon that dawned up in the sky.

--------------------------------------------------
