#+BEGIN_COMMENT
.. title: Yellow Balloon
.. slug: yellow-balloon
.. date: 2021-08-19 11:30:15 UTC+05:30
.. tags: poem
.. category: English
.. link: 
.. description: 
.. type: text
#+END_COMMENT

#+OPTIONS: \n:t

# Author Awake
The night, soothingly quiet, Poet awoke in her bed,
A story emerged, an idea raged inside her head.
She leapt to her desk, and started scribbling away,
In hope that the memory of her dream would stay.

# Hammock Girl
Lying on a hammock she thought-thought,
About last night’s dream that she caught.
A story that she wanted to tell-tell,
But out of her mind it suddenly fell.

# Paradise world
Something about a familiar young girl,
Who wore a necklace made of pearl.
Ah..! the curious world inside a crystal bowl,
And indeed a villain to make the story whole!

# Villain
Enter the villain, with a yellow balloon in his hand,
Seven feet tall, skinny lad was all tanned.
With him he brought his own music band,
That played popular songs which were banned.

# Conversation
Yellow balloon hovered above his head like a halo,
Her eyes twinkled as she went to say hello.
Will you give me that yellow balloon that I crave?
Quid pro quo the pearl necklace, I will take it to my grave.

I will not give you the necklace.
Is that so young lady? why? may I ask?
Because you’re the villain in this story,
Yes! but villains are also part of history.

Don't villains invariably lose in the end?
Right you are! here is your yellow balloon, my friend.
She reached out for the balloon, and he let it fly,
Hahahaa! where's the fun in not letting it touch the sky.

# Hammock Girl Awake
She woke up with a start, still lying on her hammock,
The pearl necklace planted safely on her neck.
She slid into her chair, and started scribbling away,
In hope that the memory of her dream would stay.

# Yellow Balloon
The night, soothingly quiet, is coming to its end,
As Poet looked outside the balcony, facing the wind.
Words rhyming on her book; Pearl necklace on her neck,
She smiled at an yellow balloon dawning up in the sky.

--------------------------------------------------
