#+BEGIN_COMMENT
.. title: Yellow Balloon
.. slug: yellow-balloon
.. date: 2021-08-19 11:30:15 UTC+05:30
.. tags: poem
.. category: English
.. link: 
.. description: 
.. type: text
#+END_COMMENT

#+OPTIONS: \n:t

# Author Awake
The night, soothingly quiet, Poet awoke in her bed,
Eyes wide, a story unsaid, is raging in her head.
She leapt to her desk and started scribbling away,
In hope that the memory of her dream would stay.

# Hammock Girl
Lying on a hammock she thought,
About a piquant dream she caught. 
An unsaid story that she must tell,
But out of her mind it suddenly fell.

# Paradise world
Something about a familiar young girl,
Who wore a necklace made of pearl.
Ah..! the curious world inside a crystal bowl,
And indeed a villain to make the story whole!

# Villain
Enter the villain, with a yellow balloon in his hand,
Seven feet tall, skinny lad was all tanned.
With him he brought his own music band,
Popular songs that it played were all banned.

# Conversation
Yellow balloon hovered above his head like a halo,
Her eyes twinkled as she went to say hello.
Will you give me that yellow balloon that I crave?
Quid pro quo the pearl necklace, I will take it to my grave.

The necklace I will not give, no, no, no!
You think I will cheat, Is that so?
Because you’re the villain in this story,
Yes! but villains are also part of history.

Don't villains invariably lose in the end?
Right you are! here, take the balloon, my friend.
She reached out for the balloon, and he let it fly,
Hahahaa! where's the fun in not letting it touch the sky.

# Hammock Girl Awake
She woke up with a start, still lying on her hammock,
The pearl necklace was planted safely on her neck.
She opened her book and started scribbling away,
In hope that the memory of her dream would stay.

# Yellow Balloon
The night, soothingly quiet, is coming to its end,
The poet, stood in her balcony, facing the cold wind.
Words rhyming on her book, Necklace shining on her neck,
She smiled at an yellow balloon that dawned up in the sky.

--------------------------------------------------
